### ISSUE TITLE
NoClassDefFoundError: java/util/HashMap$Entry on JDK1.8

### ISSUE THREAD

**Issue by keima** [tmiyamon/gradle-mdicons#4]
Hi,

I encountered NoClassDefFoundError when I added gradle-mdicons definition on gradle file and Android Studio's button "Sync Project".
(This error is also occuered ./gradlew tasks )

Stacktrace is here: https://gist.github.com/keima/cd3a46b6c68d52ac738f
classpath 'com.tmiyamon:gradle-mdicons:0.2.1'

I think this error causes jdk1.8's HashMap.Entry internal changes.
Following issue is same error, isn't it?
https://github.com/nextflow-io/nextflow/issues/7

Workaround, I set jdk 1.7 path at JAVA_HOME.

**Comment by rimmer** [comment]
got the same problem
